contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #neofuse channel"
    url: https://nfcore.slack.com/channels/neofuse
    about: Discussion about the nf-core/neofuse pipeline
